### ISSUE TITLE
Drop input_country from update_download_list + parse DOI

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/trias#10]
The [gbif download list](https://github.com/trias-project/pipeline/blob/master/data/output/gbif_downloads.tsv) currently has a field `input_country`. However, there are more filters that we might set than countries, e.g. not accepting occurrences with issues or searching within a specific date range. Because:

1) We can't capture all of this in the file
2) Just listing countries gives a false impression of the actual filters
3) The [download page](https://www.gbif.org/occurrence/download/0007989-180131172636756) itself lists all filters

**I would drop `countries` from the function as a parameter and the output.** I would also drop the column from the tsv file.

Note 1: simply not providing the parameter is not an option, as it is required.

Note 2: the specific taxa list we used is still very useful though, so `input_checklist` should be kept.

---

To provide a better link to the download page, I would parse the `gbif_download_doi` within the function and **prepend it with `https://doi.org/`** (so `10.15468/dl.6cljf9` becomes https://doi.org/10.15468/dl.6cljf9). This only needs to be done for **new** lines (so no need to check this for all previous downloads).

**Comment by damianooldoni** [comment]
Yes, providing the link is very useful and the GBIF API is much nicer to read than a text file. I will do it.

**Comment by damianooldoni** [comment]
I made a new branch for it: [remove_country_from_tsv](https://github.com/trias-project/trias/tree/remove_country_from_tsv)
In order to remove column `input_country` from `gbif_downloads.tsv` in repository `pipeline`, I made a new branch in that repository as well: [remove_country_gbif_downloads](https://github.com/trias-project/pipeline/tree/remove_country_gbif_downloads)
Soon commits and PR

**Comment by peterdesmet** [comment]
Awesome, in your branch in the pipeline repo, can you immediately update the function names as well? Thanks!

**Comment by damianooldoni** [comment]
`countries` removed in call to `update_download_list` in pipeline `get_occurrences.Rmd`.

**Comment by damianooldoni** [comment]
Done. See PR #13
