### ISSUE TITLE
Order of year bins in `visualize_pathways_year_level1`

### ISSUE THREAD

**Issue by mvarewyck** [trias-project/trias#100]
The order of year bins is not logic if the first_observed happens after the function argument `from`. So when no observations are in the year trade-off.
Note: this might also be a bug in `visualize_pathways_year_level2` (not tested)

I think this can be fixed by including some kind of check `min(data$first_observed, na.rm = TRUE) < from` for defining the bin level order [here](https://github.com/trias-project/trias/blob/main/R/visualize_pathways_year_level1.R#L441-L445)

Example code and screenshots below.

_Default example_
```
library(readr)
datafile <- paste0(
  "https://raw.githubusercontent.com/trias-project/indicators/master/data/",
  "interim/data_input_checklist_indicators.tsv"
)
data <- read_tsv(datafile,
  na = "",
  col_types = cols(
    .default = col_character(),
    key = col_double(),
    nubKey = col_double(),
    speciesKey = col_double(),
    first_observed = col_double(),
    last_observed = col_double()
  )
)
# All taxa
visualize_pathways_year_level1(data)
```
![plot1](https://user-images.githubusercontent.com/22143743/216037870-ad306369-4bc7-4c2e-ab18-f7df55cb0d83.png)

_This doesn't work well_
```
data <- data[data$first_observed > 1960, ]
visualize_pathways_year_level1(data)
```
![plot2](https://user-images.githubusercontent.com/22143743/216037881-6b634fe5-b059-477d-ac89-098a2bad551c.png)

_This works well_
```
data <- data[data$first_observed > 1960, ]
visualize_pathways_year_level1(data, from = 1980)
```
![plot3](https://user-images.githubusercontent.com/22143743/216037896-b0de6159-5e27-4064-acfa-9c1290817258.png)

**Comment by damianooldoni** [comment]
Good catch @mvarewyck! Thanks for contacting me and providing me such useful reproducible examples. I will work on it.
