### ISSUE TITLE
Improve annotation when GAM cannot assess emerging status

### ISSUE THREAD

**Issue by damianooldoni** [trias-project/trias#103]
An annotation is added when no emerging status can be assesses by GAM:
`"The emergence status cannot be assessed"`. This was done in https://github.com/trias-project/trias/pull/96 after https://github.com/trias-project/trias/issues/91.

In the TrIAS [emerging status workflow](https://trias-project.github.io/indicators/07_occurrence_indicators_modelling.html) we use decision rules to assess the emerging status if GAM cannot help, so that annotation should be replace by:

`"The emerging status cannot be assessed by GAM"`

Notice also that I would replace `emergence` with `emerging` as we use in workflows everywhere.

See e.g. this screenshot taken from [this](https://raw.githubusercontent.com/trias-project/indicators/main/data/output/GAM_outputs/GAM_observations_basic_8701771_Obama%20nungara.png) GAM output plot as reference for this issue. @timadriaens, @mvarewyck: let me know if you agree on this.
![image](https://user-images.githubusercontent.com/33662631/217521804-2c4eebe4-239e-43c0-9756-8f8aacd564c9.png)

**Comment by mvarewyck** [comment]
Fine for me.

**Comment by timadriaens** [comment]
I would leave out the "emerging/emergence" and just say ""The status cannot be assessed by GAM"

**Comment by SanderDevisscher** [comment]
I agree with @timadriaens

**Comment by damianooldoni** [comment]
Thanks for fast reply. I will implement your suggestion.
