### ISSUE TITLE
Trying to run climate matching script

### ISSUE THREAD

**Issue by arnaudjacobs** [trias-project/trias#107]
Hello @SanderDevisscher 
I'm trying to run and understand the climate matching script for ornamentals (first with the dataset used initially for Antoine Dumortier).

I'm getting the following error when running the "climate matching function chunk"
_Error in climate_match(region = "Belgium", taxonkey = taxonkeys_sub, BasisOfRecord = c("HUMAN_OBSERVATION",  : 
  unused arguments (taxonkey = taxonkeys_sub, zipfile = zipfile)_

What is that zipfile exactly?
Thanks for enlightening me

**Comment by damianooldoni** [comment]
Hi @arnaudjacobs! I am not Sander, but as maintainer of the package I can answer to your question as well.

To avoid triggering GBIF downloads over and over, @SanderDevisscher added an optional argument, `zipfile`: you can use an already downloaded GBIF occurrence download which you have previously imported on your machine as a **zipfile**.

More about the function and its arguments in the online documentation: https://trias-project.github.io/trias/reference/climate_match.html
or via `?` help in R:

```r
library(trias)
?climate_match
```

**Comment by arnaudjacobs** [comment]
Thanks a lot for the clarifications @damianooldoni ! :)

**Comment by damianooldoni** [comment]
You are welcome! 👍 
As any package maintainer, I am very happy to see this package can be useful somehow. 
Please, feel free to open new specific issues in the future in case you have other questions.
