### ISSUE TITLE
Use releases

### ISSUE THREAD

**Issue by damianooldoni** [trias-project/trias#108]
Suggested by @mvarewyck in https://github.com/inbo/alien-species-portal/pull/56#issuecomment-1757627947. 
@mvarewyck: Do you want I create a release with the trias 2.0.3 version and one release with the version we have now: 2.0.6?

In the future I will create releases at each new version, good practice!

**Comment by mvarewyck** [comment]
> Suggested by @mvarewyck in [inbo/alien-species-portal#56 (comment)](https://github.com/inbo/alien-species-portal/pull/56#issuecomment-1757627947). @mvarewyck: Do you want I create a release with the trias 2.0.3 version and one release with the version we have now: 2.0.6?
> 
> In the future I will create releases at each new version, good practice!

Release version for 2.0.6 would be perfect, thanks!

**Comment by damianooldoni** [comment]
Done: https://github.com/trias-project/trias/tree/v2.0.6
