### ISSUE TITLE
rewrite code avoiding using sp and rworldmap

### ISSUE THREAD

**Issue by damianooldoni** [trias-project/trias#110]
@SanderDevisscher: the climate function is using sp package. rworldmap is also used, which relies on sp. 

It's time to move to sf. In this way we don't need to use packages rgeos and rgdal which are archived since October 2023 and not more available. See failures of GitHub actions. This is not only important for the authomatic checks of this package, but as you are authomatising the indicators workflow, using the trias package in your GitHub Actions will fail.

**Comment by SanderDevisscher** [comment]
I'll look into it

**Comment by SanderDevisscher** [comment]
@soriadelva will look into this under my supervision.

**Comment by damianooldoni** [comment]
Thanks for the update. I have added her just now to trias as member.

**Comment by soriadelva** [comment]
@damianooldoni, the RDA data files currently provide the climate data as SpatialPolygonsDataFrame and Sander and me were wondering if it could be useful to recode them as GeoJSON?

**Comment by soriadelva** [comment]
@damianooldoni thanks for the reply! I'll convert them to two lists of sf.
