### ISSUE TITLE
Tests of package (via devtools::check() ) indicates an error and warnings

### ISSUE THREAD

**Issue by soriadelva** [trias-project/trias#113]
Devtools::check() indicates an error and warnings with the package in the part where testthat.R is being run. This happens also in the main. Specifically, in test-input_apply_gam.R it gives the following **error**:

Error in `dplyr::select(., smooth, var, data, derivative, se, crit, lower, 
    upper)`: Can't select columns that don't exist.
✖ Column `smooth` doesn't exist.

**Warnings** include warnings of the following type :

-  Use of .data in tidyselect expressions was deprecated in tidyselect 1.2.0.
ℹ Please use `"rank"` instead of `.data$rank`

-  Using an external vector in selections was deprecated in tidyselect 1.1.0.
ℹ Please use `all_of()` or `any_of()` instead.
   Was:
  data %>% select(name_col_taxa)
  Now:
  data %>% select(all_of(name_col_taxa))

Will wait to merge branch with the main until this is solved.

**Comment by damianooldoni** [comment]
The reason are breaking changes in the last version of gratia: https://gavinsimpson.github.io/gratia/news/index.html#breaking-changes-0-9-0
I will try to solve this asap.

**Comment by damianooldoni** [comment]
Hi @soriadelva 👋 
I think I solved this. Could you please check it by installing the trias package from PR #117 and review that PR? Thanks.

**Comment by soriadelva** [comment]
> Hi @soriadelva 👋 I think I solved this. Could you please check it by installing the trias package from PR #117 and review that PR? Thanks.

Works like a charm  👌
