### ISSUE TITLE
Filter out duplicates for indicator_native_range_year

### ISSUE THREAD

**Issue by mvarewyck** [trias-project/trias#115]
As described in https://github.com/inbo/alien-species-portal/issues/90#issue-2227465355
The plot includes duplicate records, which are ideally filtered out on trias side.

**Comment by mvarewyck** [comment]
@damianooldoni I have code ready to fix this but I'm not able to push to (separate branch of) the repos

**Comment by damianooldoni** [comment]
Thanks @mvarewyck. I will add you to the repo just now. Please, accept the invitation you will receive in a minute.
