### ISSUE TITLE
Climate_match, deprecated feature?

### ISSUE THREAD

**Issue by arnaudjacobs** [trias-project/trias#120]
Hello @damianooldoni 

I was trying to use again the climate_match function that I was routinely using the last months and now I'm getting this error message:

Error in UseMethod("st_crs<-") : 
  no applicable method for 'st_crs<-' applied to an object of class "c('SpatialPolygonsDataFrame', 'SpatialPolygons', 'Spatial')"
In addition: Warning message:
The `returnclass` argument of `ne_download()` sp as of rnaturalearth 1.0.0.
ℹ Please use `sf` objects with {rnaturalearth}, support for Spatial objects (sp) will be removed in a
  future release of the package.
ℹ The deprecated feature was likely used in the trias package.
  Please report the issue at <https://github.com/trias-project/trias/issues>.
Backtrace:
    ▆
 1. └─trias::climate_match(...)
 2.   └─rnaturalearth::ne_countries()
 3.     └─rnaturalearth:::deprecate_sp("ne_download(returnclass = 'sp')")

I understand there might a deprecated function within the trias package?
Thanks for the help!
Arnaud

**Comment by damianooldoni** [comment]
Hi @arnaudjacobs! Thanks for reaching us.

Yes, we have pushed a new version of trias R package where we have refactored the function `climate_match()` so that it relies on [sf](https://r-spatial.github.io/sf/) instead of sp. This was really needed as sp was built on old packages which were archived and not anymore available (unless already installed locally). In other words: sf is the present and the future of spatial data in R.

If you pass sp objects, please convert them to sf  via sf function `st_as_sf()` first. See example here below:

``` r
# Create a dummy SpatialPointsDataFrame (sp)
data(meuse, package = "sp")
sp::coordinates(meuse) <- ~x+y
sp::proj4string(meuse) <- sp::CRS("EPSG:28992")

# Transform to sf
meuse_sf <- sf::st_as_sf(meuse)
head(meuse_sf, n = 3)
#> Simple feature collection with 3 features and 12 fields
#> Geometry type: POINT
#> Dimension:     XY
#> Bounding box:  xmin: 181025 ymin: 333537 xmax: 181165 ymax: 333611
#> Projected CRS: Amersfoort / RD New
#>   cadmium copper lead zinc  elev       dist   om ffreq soil lime landuse dist.m
#> 1    11.7     85  299 1022 7.909 0.00135803 13.6     1    1    1      Ah     50
#> 2     8.6     81  277 1141 6.983 0.01222430 14.0     1    1    1      Ah     30
#> 3     6.5     68  199  640 7.800 0.10302900 13.0     1    1    1      Ah    150
#>                geometry
#> 1 POINT (181072 333611)
#> 2 POINT (181025 333558)
#> 3 POINT (181165 333537)
```

<sup>Created on 2024-05-02 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

I hope this helps.

**Comment by arnaudjacobs** [comment]
Thanks @damianooldoni for your quick answer and explaination

I'm using the function for matching species on Belgium map/climate, with that script:
```
output <- climate_match(region = "Belgium",
                        taxon_key = taxonkeys_sub,
                        BasisOfRecord = c("HUMAN_OBSERVATION", "PRESERVED_SPECIMEN", "UNKNOWN"),
                        cm_limit = 0.01,
                        n_limit = 5,
                        maps = FALSE)
```

 So if I'm correct the sp/sf object here would be region = "Belgium".  But I cannot find that object to transform it to an sf object...

Any advice? :)

**Comment by damianooldoni** [comment]
I tested your code using `taxon_key = 1031394` and everything works fine on my laptop. Did you update the trias package by running `devtools::install_github("trias-project/trias")` as shown in [Installation](https://trias-project.github.io/trias/#installation) section of the trias homepage? To do so, I recommend to close first all RStudio sessions you have open and run the package update from a new session. The reason I tell this is that from your error message it seems that you are still using the "old" trias package where `climate_match()` function was based on sp (I see `st_crs() <-` commando which is not present anymore).

If I run `devtools::session_info()`, I can read that I have trias v trias 2.2.0 installed. I wonder if you have the same version running on your machine.

**Comment by arnaudjacobs** [comment]
Thanks for the help! It now works after having restarted the session and updated all related packages. That's a relief :)
I was already using trias 2.2.0 but probably I omitted to update something else...That's what happens to non frequent R users :D
Again your reactivity was much appreciated!

**Comment by damianooldoni** [comment]
You are welcome 👍
