### ISSUE TITLE
new release >= 2.0.8

### ISSUE THREAD

**Issue by mvarewyck** [trias-project/trias#123]
Could you please [release](https://github.com/trias-project/trias/releases) a new version of trias which has at least the changes from version 2.0.8?
We need it as a dependency in the [alien-species-portal](https://github.com/inbo/alien-species-portal/blob/fix_v1.0.0/alienSpecies/DESCRIPTION#L48)
Thanks a lot!

**Comment by damianooldoni** [comment]
Nice catch! I thought I have done it already, but I didn't apparently. I will do it immediately. Stay tuned 📻

**Comment by damianooldoni** [comment]
Tags and correspondent releases created for the versions:
- 2.0.8
- 2.1.0
- 2.2.0
See [releases](https://github.com/trias-project/trias/releases) page.

I paid extra attention to add the tags at the time of the specific commit the tags are pointing to. I followed the instructions in a tutorial online: https://www.delftstack.com/howto/git/git-tag-commit/

**Comment by damianooldoni** [comment]
I released also the very last changes about the authors of the trias package ([v2.2.1](https://github.com/trias-project/trias/releases/tag/v2.2.1)). 
@mvarewyck: welcome to the club 🥳 Your inputs are improving trias package definitely a lot!
