### ISSUE TITLE
Update package contributors/authors

### ISSUE THREAD

**Issue by damianooldoni** [trias-project/trias#124]
person | from | to
--- | --- | ---
@peterdesmet | author | contributor
@mvarewyck | - | contributor

@mvarewyck: do you have an ORCID? I cannot find it. Thanks.

**Comment by mvarewyck** [comment]
> @mvarewyck: do you have an ORCID? I cannot find it. Thanks.

0009-0003-0496-0447

**Comment by damianooldoni** [comment]
Done in #125
