### ISSUE TITLE
Fix plot size while saving GAM modelling plots

### ISSUE THREAD

**Issue by damianooldoni** [trias-project/trias#126]
We save plots using `ggplot::ggsave()` function in `trias::apply_gam()`:
https://github.com/trias-project/trias/blob/b9e68fd1ac1327eccb54ec0482a76f3f99f9859d/R/apply_gam.R#L743C5-L743C52

However, the returned png can have no stable dimension. Based on ggsave documentation (bold the part of interest):

> width, height: Plot size in units expressed by the units argument. **If not supplied, uses the size of the current graphics device.**

So, we should provide `width` and `height` default values to allow stability along different runs of the function.

**Comment by mvarewyck** [comment]
> @mvarewyck: no idea whether you are using `trias::apply_gam()`, probably yes. Do you agree on this? Do you have a preference for the width and height of the plots?

We use `trias::apply_gam()` always with the default option `save = FALSE`. So for us it doesn't matter.
