### ISSUE TITLE
Add function spread_with_duplicates

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/trias#16]
Create a function from functionality developed for the [pipeline](https://github.com/trias-project/pipeline) to spread a dataframe with duplicate entries:

taxon_key | type | description
--- | --- | ---
1 | A | R
1 | B | S
1 | C | T
1 | C | X

With:

```r
df %>% spread_with_duplicates(type, description)
```

To:

taxon_key | A | B | C
--- | --- | --- | ---
1 | R | S | T
1 | R | S | X

Note that the regular dplyr spread:

```r
df %>% spread(type, description)
```

Would throw an error because of the duplicate entries.

---

Might be good to suggest this functionality to dplyr first? /cc @stijnvanhoey @damianooldoni

**Comment by damianooldoni** [comment]
A fast check on [dplyr issue page](https://github.com/tidyverse/dplyr/issues) and a search on Google doesn't return any link to a GitHub issue, just ad hoc (**no tidy!**) solutions on Stackoverflow, like [this one](https://stackoverflow.com/questions/43259380/spread-with-duplicate-identifiers-using-tidyverse-and), proposed in many variants in other internet sites. 
At the moment, I implemented it via a small function and a pipe containing `purr` functions in `build_checklist_indicators.Rmd` of `pipeline` repo, see PR https://github.com/trias-project/pipeline/pull/32.

**Comment by peterdesmet** [comment]
So, do you agree to develop our own function and later maybe notify dplyr developers?

**Comment by damianooldoni** [comment]
Own function ready (see #17). Give a look, if you have time for it. Thanks.

**Comment by damianooldoni** [comment]
Function written and branch merged. @peterdesmet: time to close the issue?
