### ISSUE TITLE
Issues returned as codes by name_usage()

### ISSUE THREAD

**Issue by damianooldoni** [trias-project/trias#22]
The last version of `name_usage()` solves the problem of returning more rows than taxa (see issue https://github.com/ropensci/rgbif/issues/324). However, the field `issues` doesn't contain the issue names, but the codes which are not easy to interpret without using the table returned by `rgbif::name_issues()`.
My proposal is to use the pipes in my gist [damianooldoni/get_df_with_issues](https://gist.github.com/damianooldoni/c305a4383fc4ea0518871d5fa7fc550e) in our `get_taxa.Rmd` pipeline to substitute the codes with the corresponding issues.
@peterdesmet : what do you think about? Should we code this step in a trias function? I don't think so, at least for the moment.

**Comment by peterdesmet** [comment]
What do the codes look like?

**Comment by damianooldoni** [comment]
The code is in my gist as mentioned above. Does the link doesn't work? 
In any case, here below the pipe:
```r
# Table codes, issues, descriptions
issues_df <- rgbif::name_issues()

# Change codes into their corresponding issues 
example_duplicates_with_issues <- example_duplicates %>% 
  separate_rows(issues, sep = ",") %>%
  left_join(issues_df, by = c("issues" = "code")) %>%
  mutate(issues = issue) %>%
  select(-c(issue, description)) %>%
  group_by_at(vars(-issues)) %>%
  summarise(issues = paste(issues, collapse  = ","))
```

**Comment by damianooldoni** [comment]
Just an update: I still haven't found time to improve at rgbif level (ropensci/rgbif/issues/326). Is this issue still an "issue" of the unified checklist pipeline? I don't think so.

**Comment by peterdesmet** [comment]
No, don’t think so. If I encounter an issue I will let you know.
