### ISSUE TITLE
How to manage changes of synonym in verify_taxa()

### ISSUE THREAD

**Issue by damianooldoni** [trias-project/trias#23]
While running pipeline for unified checklist I encountered this situation.
I have a taxon in verification table (`verified_taxa`) from Manual of Alien Plants: `Oxalis stricta L.` (`key` = [`141266323`](http://api.gbif.org/v1/species/141266323)) added in 2018-08-01. At that time it was recognized by GBIF Backbone as `Oxalis stricta L.` ([9823072](http://api.gbif.org/v1/species/9823072)) and linked by synonym relation to `Oxalis corniculata L.` ([8427624](http://api.gbif.org/v1/species/8427624)). However, I get now as input a data.frame `checklist_taxa` where the same taxon is now linked to a new GBIF Backbone key ([2891666](http://api.gbif.org/v1/species/2891666)) and a new synonym, `Oxalis dillenii` ([2891677](http://api.gbif.org/v1/species/2891677)). Notice that the GBIF Backbone scientific name didn't change.

@peterdesmet : is it possible? I find slightly strange that two GBIF backbone keys (`9823072` and `2891666`) share the same scientific name. Are they not same taxon? I notice that the most recent key has the (deprecated) `nubKey` value while the old one doesn't. As `verify_taxa()` has been implemented so far, it doesn't take explicitly into account changes of synonym relation, so a second row is added linking to new synonym. Is it ok? But what should happen with old synonym relation? Should it be labelled as an unused taxon?

**Comment by damianooldoni** [comment]
Just to make a scheme and get the core of the problem. I agree that the function `verify_taxa()` should take into account this kind of situation:

scientificName | bb_scientificName | bb_key | accepted_key | date_added
--- | --- | --- | --- | ---
A | B | 1 | 20 | 2010-01-01
A | B | 1 | 30 | 2018-01-01

and add the remark `unused taxa` to the first row. However, the situation I presented in this issue is in some way different:

scientificName | bb_scientificName | bb_key | accepted_key | date_added
--- | --- | --- | --- | ---
A | B | 1 | 20 | 2010-01-01
A | B | 2 | 30 | 2018-01-01

It is not just an update of synonym relation, but a new couple `bb_key` - `bb_acceptedKey`, although the scientificName and the `bb_scientificName` are the same and we are obviously speaking about the same species.

Returning to the concrete casus of `Oxalis stricta L.`, actually I see a link between the GbIF backbone keys [9823072](http://api.gbif.org/v1/species/9823072) and [2891666](http://api.gbif.org/v1/species/2891666): there is a `proParteKey` field in both taxa. The `proParteKey` of the first taxa is equal to 2891666, thus pointing to the second taxa.But the question is the following: is adding `bb_proParteKey` the best solution for us? I don't think so.

**Comment by peterdesmet** [comment]
Before looking for a solution, @qgroom can maybe explain what is going here taxonomically? It’s about Oxalis after all. 😊

**Comment by damianooldoni** [comment]
This issue can be closed as this problem will not occur in the last version of `verify_taxa()`.
