### ISSUE TITLE
How verify_taxa() handles taxa which don't need manual verification

### ISSUE THREAD

**Issue by damianooldoni** [trias-project/trias#24]
Three options:
1. `verify_taxa()` doesn't accepts taxa with `bb_taxonomicStatus` equal to `ACCEPTED` or `DOUBTFUL`, so throwing an error. In other words, the function doesn't accept taxa which don't need verification.
2. `verify_taxa()` throws a warning saying: `n taxa do not need verification. They will be removed. Taxon keys: ` and a list of related taxon keys follows.
3. `verify_taxa()` doesn't throw any warning. It just filter these taxa out.
4. `verify_taxa()` adds these taxa to output as well with `verification_key = bb_taxonKey`.

I would like to ask you, @peterdesmet, which option do you prefer?
I implemented option 2 in order to be flexible, but at the same time informative.
Let me know your meaning about. Thanks.

**Comment by peterdesmet** [comment]
Well, if the function is smart enough to detect ACCEPTED or DOUBTFUL anyway, then I would opt for option 4, returning the original df, with the `verificationKey` column added. That way the user doesn't have to set the `verificationKey = bb_taxonKey` themselves and more importantly, doesn't have to join the verified taxa back with the original one.

I would also return a list two objects:

- The verified dataframe
- Extra information: `new_synonyms`, `unused_taxa`, `updated_scientificName` (any other?)

That nicely separates the important information (the verified df) and ancillary information (any updates to the verification_file). So the user can do:

```R
my_taxa, info <-
  my_taxa %>% verify_taxa(verification_file)

info$new_synonyms
info$unused_taxa
info$updated_scientificName
```

**Comment by damianooldoni** [comment]
Ok, I was just thinking defensively, maybe too defensively. I will opt for option 4.  :+1: 

About return. The actual status `verify_taxa()` output is a list of 8 dataframes:

1. `verified_taxa`
2. `new_synonyms`
3. `new_unmatched_taxa`
4. `outdated_taxa` (the old "unused taxa", see issue of yesterday, https://github.com/trias-project/unified-checklist/issues/17)
5. `updated_scientificName`
6. `updated_acceptedName`
7. `duplicates_taxa` (taxa present in more checklists)
8. `check_verificationKey` (check verification keys for manual typos by taxonomists. Based on trias function `gbif_verify_keys()`)

I will split it in a list of two with the second element, called `info`, a list itself containing the other 7 dfs.

**Comment by damianooldoni** [comment]
We agree on this output structure:

```r
verify_taxa(my_taxa, verification_file) {
  ...
  return(
    list(
      my_taxa = my_taxa,
      verification_file = verification_file,
      info = info
    )
  )
}
```
where info contains the ancillary dataframes.

**Comment by damianooldoni** [comment]
Done.
