### ISSUE TITLE
What ancillary df duplicates_taxa should contain?

### ISSUE THREAD

**Issue by damianooldoni** [trias-project/trias#26]
In old version of `verify_taxa` the df output `duplicates_taxa` contained taxa from different checklists which with same scientific name.
In new `verify_taxa()`, I propose to use `duplicates_taxa` to collect all taxa which point to same `bb_key`-`bb_acceptedKey`. 

Example. The taxa here below would be in duplicates_taxa:

taxonKey | scientificName | bb_key | bb_acceptedKey
--- | --- | --- | ---
1 | A | 10 | 15
2 | B | 10 | 15
3 | C | 10 | 15

Drawback of this implementation: taxa without match to GBIF Backbone would be not included. So the following two taxa which are very likely the same species, would be not returned in `duplicates_taxa`:

taxonKey | scientificName | bb_key | bb_acceptedKey
--- | --- | --- | ---
4 | E | NA | NA
5 | E | NA | NA

I can live with that :smile: @peterdesmet : you too? It is actually a question about the meaning we want to give to the expression "duplicates taxa". As we use now a key-triplets (`taxonkey` - `bb_key` - `bb_acceptedKey`) to identify unique taxa instead of names, I think using `bb_key` - `bb_acceptedKey` sounds to be the best option.

**Comment by peterdesmet** [comment]
As discussed, just using keys (and not names) for this df is fine. I would simply call the df “duplicates”

**Comment by damianooldoni** [comment]
Allright.

**Comment by damianooldoni** [comment]
Done.
