### ISSUE TITLE
Order of the taxa returned by verify_taxa()

### ISSUE THREAD

**Issue by damianooldoni** [trias-project/trias#27]
As already decided, the new implementation of `verify_taxa(taxa, verified_taxa)` updates and returns the two input dfs.
To do it, some joins and row binding operations are performed so the order of the taxa is typically not the same as in the input dfs. I split the issue in two:
### order of taxa in `taxa`
I propose to return the taxa in the same order as in the input df for better comparison.
### order of taxa in `verified_taxa`
I would put outdated taxa (taxa not needed to be checked anymore) at the very end. Would we order them by date? the newest ones first? Maybe a detail, but still...

**Comment by peterdesmet** [comment]
What you suggest is good: same order for taxa, reverse chronological for verified_taxa. Come to think of it, taxa_to_verify might be a better df name?

**Comment by damianooldoni** [comment]
Done.
