### ISSUE TITLE
Verify taxa: ungroup() info$duplicates

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/trias#29]
So it can be grouped by user without ungrouping first.

**Comment by peterdesmet** [comment]
Steps I currently use to circumvent this:

https://github.com/trias-project/unified-checklist/blob/b91446ba491f2aed77e0d5ef303108f6b554c248/src/verify_taxa.Rmd#L137

**Comment by damianooldoni** [comment]
Yes, you are right. Thanks for discovering the bug. 
I will check all output dataframes.

**Comment by damianooldoni** [comment]
I think we can close this issue as it has been solved by PR #32.
