### ISSUE TITLE
Included verifiedBy column after remarks

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/trias#31]
Add a column `verifiedBy` in `verification` input and output. The content should remain unaltered (just like `remarks`).

**Comment by damianooldoni** [comment]
`remarks` is not an unaltered field: the label `Outdated taxa` can be added or removed by verify_taxa() if needed.

**Comment by damianooldoni** [comment]
@peterdesmet : where do you want column `verifiedBy` in `verification` df?
I would suggest the sequence: ..., `verificationkey`, `remarks`, `verifiedBy`, `dateAdded`, `outdated`.

**Comment by damianooldoni** [comment]
While writing tests, I am noticing that we should avoid that `verificationKey` is empty and `verifiedBy` not. 
I would remove any `verifiedBy` if `verificationKey` is empty, obviously providing a warning with the deleted `verifiedBy` values. @peterdesmet : what do you think?

**Comment by peterdesmet** [comment]
1. I would not write that kind of information to `remarks` (anymore): we have the field `outdated` for that (now).
2. And I would not empty `verifiedBy` or `remarks` by the script. For example, a taxa might be verified, but it was decided not to populate the `verificationKey`.

**Comment by damianooldoni** [comment]
Point 1: reasonable.
Point 2: reasonable as well.
So, I will simplify the function and the related tests as well.
