### ISSUE TITLE
Function has_distribution()

### ISSUE THREAD

**Issue by damianooldoni** [trias-project/trias#4]
```r
has_distribution <- function(taxon_key, ...) 
```
## Parameters
- [ ] `taxon_key`: single taxon key (numeric or character)
### Optional parameters
- [ ] These [GBIF distribution properties](http://rs.gbif.org/extension/gbif/1.0/distribution.xml) and their API synonyms. They have to be passed as single values (if single) or vectors.
    - `countryCode` = `country`
    - `occurrenceStatus` = `status`
    - `establishmentMeans`
- [ ] If any property passed to function does not exist: assert error
- [ ] Most of the distribution parameters can take many inputs, and treated as ’OR’ (e.g., a or b or c)

Example:

```r
has_distribution(134086855, countryCode = c("BE", "NL", "LU"), 
                          establishmentMeans  = "INTRODUCED", status = c("PRESENT", "DOUBTFUL"))
``` 

## Return

- [ ] A logical (`TRUE` or `FALSE`)

From the example above, return `TRUE` if the taxon 134086855 has at **least one distribution** with:

1. `BE`, `NL` **OR** `LU` in field countryCode **AND**
2. `INTRODUCED` in field establishmentMeans **AND**
3. `PRESENT` **OR** `DOUBTFUL` in field occurrenceStatus

## Documentation
- [ ] Document all above as succinct as possible with roxygen

**Comment by peterdesmet** [comment]
Supporting all GBIF distribution properties is harder to implement: for some we might want “contain” rather than a full match. I would only implement those I indicated in bold, which are all vocab controlled.

**Comment by damianooldoni** [comment]
Yes, and there is another point:
distribution of *Manual of the Alien Plants of Belgium*, for example, contains the following distribution properties:
`taxonKey`,  `locationId`, `locality`, `country`, `status`, `temporal`, which are not all compatible with [GBIF distribution properties](http://rs.gbif.org/extension/gbif/1.0/distribution.xml).
 For example, in GBIF: `countryCode` instead of `country`, `occurrenceStatus` instead of `status` and `eventDate` instead of `temporal`. So, I will not check compatibility with GBIF distribution properties.

**Comment by damianooldoni** [comment]
While checking further `has_synonyms` with real species distribution, I found that the distributions of taxa of *Manual of Alien Plants of Belgium* do not contain `establishmentMeans` ([example](http://api.gbif.org/v1/species/134086855/distributions)). However, it is available via verbatim ([example](http://api.gbif.org/v1/species/134086855/verbatim)).

**Comment by peterdesmet** [comment]
Two questions = two answers:

1. The GBIF API renames some of the properties:

* `taxonKey`
* `locationID`
* `locality`
* **`countryCode`** → **`country`**
* `lifeStage`
* **`occurrenceStatus`**  → **`status`**
* `threatStatus`
* **`establishmentMeans`**
* `appendixCITES`
* `eventDate`  → `temporal`
* `startDayOfYear`
* `endDayOfYear`
* `source`
* `occurrenceRemarks`
* `datasetID`
* not in checklist → `sourceTaxonKey` (for backbone species only)

Our function should accept all bolded parameters (INCLUDING THEIR ALTERNATIVE NAMES). I've updated the issue body.

2. The reason why `establishmentMeans` is not available for the plants is because of https://github.com/trias-project/alien-plants-belgium/issues/35 and should be solved in next publication.

**Comment by damianooldoni** [comment]
`has_distribution` is ready for review and testing by @peterdesmet.
Based on last comments, next behaviors have been implemented:

```r
has_distribution(occurrenceStatus = ..., countryCode = ...)
```
is equivalent to 

```r
has_distribution(status = ..., country = ...) 
```
Warnings are provided: *"countryCode renamed to country", "occurrenceStatus renamed to status"*

If `countryCode` and `country` both present: `countryCode` property removed and warning given:
*"country and countryCode are alternative names of the same property. countryCode removed."*

Similar behavior if `occurrenceStatus` and  `status` both present.
Moreover, the next call to `has_distribution` returns an error:
```r
has_distribution(status = "BE", status = "NL")
```
*Duplicates in property assignments. Use vectors for multiple assignments."*

**Comment by damianooldoni** [comment]
issue handled and I hope solved. See pull request https://github.com/trias-project/trias/pull/6

**Comment by damianooldoni** [comment]
I think we can close this issue.

**Comment by peterdesmet** [comment]
Indeed
