### ISSUE TITLE
Update gbif_has_distribution() to allow NOT filters

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/trias#40]
@damianooldoni, see https://github.com/trias-project/unified-checklist/issues/37: we want to update the `gbif_has_distribution` filter used in the unified checklist so that we can filter:

```R
trias::gbif_has_distribution(
      taxon_key = x,
      country = "BE",
      establishmentMeans = c("INTRODUCED", "NATURALISED", "INVASIVE", "ASSISTED COLONISATION"),
      status != c("ABSENT", "EXCLUDED", "DOUBTFUL")
    )
```

I.e. where the filter `status` does NOT include `ABSENT`, `EXCLUDED`, or `DOUBTFUL`. Not sure how to pass such a parameter. It would be cool if we could pass on a dplyr selection, but not sure how to do that.

Maybe we should drop the use of the `gbif_has_distribution()` function, get all distributions, and then use dplyr filters to select those taxa that match what we need.

**Comment by damianooldoni** [comment]
As the function is not used anymore and it is even better to reduce API reguests, I think that this issue can be closed, right?

**Comment by peterdesmet** [comment]
Yep. Should have done this earlier myself.
