### ISSUE TITLE
Enable custom axis labs for indicators

### ISSUE THREAD

**Issue by SanderDevisscher** [trias-project/trias#45]
I've been trying to translate the axis labels of the graphs provided by this function [indicator_introduction_year.R](https://github.com/trias-project/trias/blob/master/R/indicator_introduction_year.R). 
But since the function exports the graph as a "Large egg" I've been unable to do it. 
If axis labels could be included as a variable in the function, with English as default, I and others would be able to translate the graphs to any language required.

This could be useful for other indicators as well.

**Comment by SanderDevisscher** [comment]
If this is considered a good idea I'm willing to implement it myself ;-)

**Comment by damianooldoni** [comment]
If this helps you or others, why not?
You can try it in a branch and then add me as reviewer of the PR :+1:

**Comment by SanderDevisscher** [comment]
OK

**Comment by damianooldoni** [comment]
Solved.
