### ISSUE TITLE
Add option "origin" to get_taxa()

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/trias#5]
Problem described at https://github.com/ropensci/rgbif/issues/288

## If tackled at rgbif (preferred)

1. Add option `origin` to `get_taxa()`
2. Directly transfer to `name_usage()` to filter

## If not tackled at rgbif

1. Add option `origin` to `get_taxa()`
2. Get results
3. Filter on data on origin

**Comment by damianooldoni** [comment]
An internal PR has been submitted in order to tackle this issue at rgbif:
https://github.com/damianooldoni/rgbif/pull/2
However, consider the fact that name_usage will not get any `origin` (see discussion at https://github.com/ropensci/rgbif/issues/288). Birefly, the point is the different behavior of API calls under `name_usage()` and `name_lookup()`.

**Comment by damianooldoni** [comment]
To solve it, I suggest to use `name_lookup()` in `get_taxa()` instead of `name_usage()`. 
We can at any moment use `name_usage()` to retrieve distribution and description by `key`.

**Comment by damianooldoni** [comment]
While adding final tests I see that mantaining the use of `name_usage()` with `checklist_keys` can be tricky.

I was implementing it like here below:
```r 
  if (!is.null(origin)) {
    origins <- stringr::str_to_lower(origin)
  }
...
checklist_taxa <- name_usage(checklist_keys = ..., limit = ...)
if (is.finite(origin)) {
  checklist_taxa %<>% filter(origin %in% origins)  
}
```

But this gives misleading results! If we apply `limit` and then select by `origin` we can miss the data we need. We should apply `limit` and `origin` simultaneously. For this reason `name_lookup()` is the best solution. 

If we want to work with `name_usage()`, then we have to get ALL data from a dataset, filtering by `origin` and then applying `limit`. With big dataframes it can be very slow.
@peterdesmet, what do you think about? Thanks.

**Comment by peterdesmet** [comment]
Considering that:

feature | name_lookup() | name_usage()
--- | --- | ---
supports dataset key(s) as input | yes (multiple) | kinda (single) 
supports taxon key(s) as input | no | yes
allows ORIGIN | yes | no
supports paging | yes, can be added | yes, recently

I would deprecate the use of `get_gbif_taxa` and directly use `name_lookup()` for checklists and `name_usage()` for lists of taxa. Most of the features we want - filter on ORIGIN for checklists, multiple dataset keys, paging, limits - are (or will be) implemented at rgbif. Doing so is clearer I think.

**Comment by damianooldoni** [comment]
Nice table :+1: 
I would still use `gbif_get_taxa` for both cases, otherwise the asymmetry in the workflow becomes even bigger. In this way, we can still provide some backbone matching information for `checklist_keys`.

**Comment by damianooldoni** [comment]
Just an update: the code is ready. However, I wait to send a PR for merging branch `add_origin`. Why? Well, in `rgbif_get_taxa.R` there is [this chunk](https://github.com/trias-project/trias/blob/add_origin/R/gbif_get_taxa.R#L127-L133) code which should be removed after internal paging will be implemented in `name_lookup()`. I would prefer to merge to `master` without this chunk code. See https://github.com/damianooldoni/rgbif/pull/3 for internal PR about this internal paging.

**Comment by damianooldoni** [comment]
branch `add_origin` has been merged and deleted. @peterdesmet, I think this issue could be closed.
