### ISSUE TITLE
Failed to install 'trias' from GitHub

### ISSUE THREAD

**Issue by qgroom** [trias-project/trias#50]
```
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          6.1                         
year           2019                        
month          07                          
day            05                          
svn rev        76782                       
language       R                           
version.string R version 3.6.1 (2019-07-05)
nickname       Action of the Toes        
```
I'm having problems installing the trias package. Any idea what I should do?

The error message is...
```
package ‘rlang’ successfully unpacked and MD5 sums checked
Error: Failed to install 'trias' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘rlang’
```

**Comment by qgroom** [comment]
I should perhaps also mention that this was after following these instructions...

```
R package with functions for TrIAS (Tracking Invasive Alien Species) project. 

## Installation

```r
install.packages("rgbif")
```

Alternatively, install development version

```r
install.packages("devtools")
devtools::install_github("trias-project/trias")
```
```

**Comment by damianooldoni** [comment]
This happens any time you try to install a package (in this case `rlang` which is required from `trias`package) while it is already loaded.

1st soft way (it could not work!): 
1. close ALL R sessions
2. restart R
3 try to install trias again 

2nd hard way (it works always :+1: ):
1. close ALL R sessions
2. get to the directory where your packages are stored and delete directory `rlang`. 
3. restart R
4 try to install trias again 

About point 2: to know where your packages are stored you can use commando `.libPath()` as shown here below:
![image](https://user-images.githubusercontent.com/33662631/69607608-dc0e9900-1025-11ea-88f1-94d224be8f66.png)

It can be that you get again similar messages for other packages. Repeat procedure above again.
Please let me know any other problem with this.

**Comment by qgroom** [comment]
Thanks!
Option 2 worked.
