### ISSUE TITLE
error produced by indicator_total_year()

### ISSUE THREAD

**Issue by eadriaensen** [trias-project/trias#55]
In using the function `indicator_total_year()`, I experienced the following error:

```
Error in matrix(if (is.null(value)) logical() else value, nrow = nr, dimnames = list(rn,  : 
  length of 'dimnames' [2] not equal to array extent
```

After looking into the source code at https://github.com/trias-project/trias/blob/master/R/indicator_total_year.R and debugging, it seems that there might be a typo at line 93:

` if (nrow(filter(df, is.na(first_observed)) > 0)) { `

should be adjusted to 

` if (nrow(filter(df, is.na(first_observed))) > 0) { `
(adjust bracket position)

Related to https://github.com/inbo/reporting-rshiny-grofwildjacht/issues/146

Could this be fixed?

**Comment by damianooldoni** [comment]
Sure I will. Thanks, @eadriaensen.
