### ISSUE TITLE
Error when using Trias to create new Indicators

### ISSUE THREAD

**Issue by SanderDevisscher** [trias-project/trias#66]
When rendering the new ias pathways indicator for the INBO website (see [#34](https://github.com/inbo/indicatoren/issues/34) I get the following error message:

```
Error: package or namespace load failed for 'trias':
 object 'all_of' is not exported by 'namespace:dplyr'
```

I think this indicates the renv(ironment) used by the indicators uses an earlier version of dplyr (0.8.5.) which does not include the 'all_of' - function. Can someone look into the minimum dplyr version required to use this function ? and maybe add it to the DESCRIPTION - file ?

**Comment by damianooldoni** [comment]
Thanks Sander! I will give a look into it.
