### ISSUE TITLE
Rename functions

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/trias#7]
I would consider renaming the functions:

* `get_taxa` → `get_gbif_taxa()`
* `has_distribution()` → `has_gbif_distribution()`

As we might have non GBIF related functions. For easier grouping, we could also consider:

* `gbif_get_taxa()`
* `gbif_has_distribution()`

@damianooldoni @stijnvanhoey thoughts?

**Comment by damianooldoni** [comment]
Both are good ideas. I vote for it :1st_place_medal:

**Comment by peterdesmet** [comment]
The top ones read more naturally...

**Comment by peterdesmet** [comment]
Ok, would update function names now then, before they are used everywhere. 😊

**Comment by damianooldoni** [comment]
Do we go for the first choice? or second one? I am still for the second one: `gbif_get_taxa()`, `gbif_has_distribution`. But no veto against the first one by me :smiley: 
And should we update the names directly in the master or do we make a branch for it?

**Comment by stijnvanhoey** [comment]
`gbif_*` +1

**Comment by peterdesmet** [comment]
Decided:

* `gbif_get_taxa()`
* `gbif_has_distribution()`

@damianooldoni on a branch please. 😊

**Comment by damianooldoni** [comment]
branch made, functions renamed and documentation modified where needed (e.g. in usage examples) (00a76777596e1a374ca6f458bdac1abf5d65b7a7, 1ff19c9ab46f17af152eb7c4c0dc0d0b6d01d153) and file renamed as well 9085734bed19ee89c67a125c85d19fabbaad1574.

**Comment by peterdesmet** [comment]
Cool, can you do a PR?

**Comment by damianooldoni** [comment]
Done: #11
