### ISSUE TITLE
Expand climate matching function with single species maps

### ISSUE THREAD

**Issue by SanderDevisscher** [trias-project/trias#74]
The idea is to expand the function from #73 with single_species_maps as a new item in the functions return list. 
These maps should be made as a sublist of taxonkeys containing a leaflet with all scenarios as basegroups.

so the final output of this expansion should be callable as `ouput$single_species_maps$taxonkey_1`

**Comment by timadriaens** [comment]
and also, to provide the option to export all the products of the procedure for a single species (occurrence data, overlay and 6 jpegs of the maps for different scenarios)

**Comment by timadriaens** [comment]
your first go looks amazing, small comment is that in any scenario the observation data are no longer superimposed but become grayish

![image](https://user-images.githubusercontent.com/16116743/124938247-6db6f880-e008-11eb-953a-3270c511013b.png)
