### ISSUE TITLE
Return dataframe used for graph

### ISSUE THREAD

**Issue by SanderDevisscher** [trias-project/trias#84]
@damianooldoni is it possible to return the summarised dataframe used for the graphs in the indicator functions ?

**Comment by damianooldoni** [comment]
indicator_native_range() returns alrady a list with `data` slot as output, so this function should not be modified, am I right, @SanderDevisscher?

**Comment by SanderDevisscher** [comment]
> `indicator_native_range()` returns alrady a list with `data` slot as output, so this function should not be modified, am I right, @SanderDevisscher?

Correct

**Comment by damianooldoni** [comment]
Functions still to be improved (function body, documentation, unit-tests):

- [ ] visualize_pathways_level1()
- [ ] visualize_pathways_level2()
- [ ] visualize_pathways_year_level1()
- [ ] visualize_pathways_year_level2()

**Comment by damianooldoni** [comment]
Is this solved? I think so. @SanderDevisscher: please check. Thanks.

**Comment by SanderDevisscher** [comment]
> Is this solved? I think so. @SanderDevisscher: please check. Thanks.

This has been solved, however there seemed to be some issues with unit tests.

**Comment by damianooldoni** [comment]
Yes, I know. Indeed, I am handling it in another issue (https://github.com/trias-project/trias/issues/92) as the unit-tests errors arise from other functions.

**Comment by damianooldoni** [comment]
There were still very few warnings (not errors) in unit-tests from `visualize_pathways_year_level_1` and `visualize_pathways_year_level_2`. Fixed in [cb418e4](https://github.com/trias-project/trias/pull/94/commits/cb418e40d4d444f0423cf026272ac7f86307c080).
So, I think this is really solved now.
