### ISSUE TITLE
Always return plot for apply_gam

### ISSUE THREAD

**Issue by mvarewyck** [trias-project/trias#91]
Currently returned plot is NULL when the emergence status cannot be assessed in `trias::apply_gam()`
For the alien species application they would like to still return a basic plot (only obs), but with a message that the emergence status cannot be assessed. Currently I've implemented a hacky solution at our side, but it might be nice if this could be incorporated in the trias package directly.

```
df_gam <- tibble(
   taxonKey = rep(3003709, 24),
   canonicalName = rep("Rosa glauca", 24),
   year = seq(1995, 2018),
   obs = c(
     1, 1, 0, 0, 0, 2, 0, 0, 1, 3, 1, 2, 0, 5, 0, 5, 4, 2, 1,
     1, 3, 3, 8, 10
   ),
   cobs = rep(0, 24)
 )
 # apply GAM to n without baseline as covariate
 tmpResult <- apply_gam(df_gam,
   y_var = "obs",
   eval_years = 2018,
   taxon_key = 3003709,
   name = "Rosa glauca",
   baseline_var = "cobs",
   verbose = TRUE
 )
 tmpResult$plot

# Hacky solution to create the plot anyhow
 df <- tmpResult$output
 df$lcl <- 10^11
 # gam failed
 trias:::plot_ribbon_em(df_plot = df, ptitle = "") +
   annotate("text", y = max(df$obs), x = max(df$year), hjust = 1, vjust = 1,
     label = "The emergence status \ncannot be assessed.", colour = "red")
```

**Comment by damianooldoni** [comment]
Thanks @mvarewyck. I will think about this. It seems to me not a bad idea, indeed. I will go on holidays up to end of July. If I find time in August, I will come back to this issue then.
